// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/Mshivam2409/AnC-Courses/models"
	"github.com/hookactions/gqlgen-relay/relay"
)

type UserConnection struct {
	Edges      []*UserEdge     `json:"edges"`
	PageInfo   *relay.PageInfo `json:"pageInfo"`
	TotalCount *int            `json:"totalCount"`
}

type UserEdge struct {
	Node   *models.User `json:"node"`
	Cursor *string      `json:"cursor"`
}
