version: "3.7"

services:
  kratos-migrate:
    image: oryd/kratos:v0.5.5-alpha.1-sqlite
    environment:
      - DSN=postgres://postgres:postgres@kdb:5432/kratos?sslmode=disable
    volumes:
      - type: bind
        source: ./.kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/.kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  server:
    depends_on:
      - kratos-migrate
    image: anc:v6
    ports:
      # - "4433:4433" # public
      - "3001:3001" # admin
      - "9001:9001"
    restart: unless-stopped
    environment:
      - KRATOS_DB=postgres://postgres:postgres@kdb:5432/kratos?sslmode=disable
      - LOG_LEAK_SENSITIVE_VALUES=true
      - COMMENTO_DB=postgres://postgres:postgres@db:5432/commento?sslmode=disable
    volumes:
      - type: bind
        source: ./supervisord.conf
        target: /etc/supervisor/conf.d/supervisord.conf
    networks:
      - intranet
  kdb:
    image: postgres
    environment:
      POSTGRES_DB: kratos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - intranet
    volumes:
      - kratos_data_volume:/var/lib/postgresql/data

  db:
    image: postgres
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - intranet
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data

  # commento:
  #   image: shivammalhotra/commento:v3
  #   ports:
  #     - 8080:8080
  #   environment:
  #     COMMENTO_ORIGIN: http://localhost:3001/.commento
  #     COMMENTO_CDN_PREFIX: http://localhost:3001/.commento
  #     COMMENTO_POSTGRES: postgres://postgres:postgres@db:5432/commento?sslmode=disable
  #   networks:
  #     - intranet
  #   depends_on:
  #     - db

volumes:
  kratos_data_volume:
  postgres_data_volume:

networks:
  intranet:
