// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Course struct {
	Title      string   `json:"title"`
	Number     string   `json:"number"`
	Credits    string   `json:"credits"`
	Offered    string   `json:"offered"`
	Contents   string   `json:"contents"`
	DriveFiles []string `json:"driveFiles"`
	ID         string   `json:"id"`
	Dept       string   `json:"dept"`
	Author     string   `json:"author"`
}

type CourseData struct {
	Course  *Course   `json:"course"`
	Reviews []*Review `json:"reviews"`
}

type Review struct {
	ID         string `json:"id"`
	Semester   string `json:"semester"`
	Instructor string `json:"instructor"`
	Grading    string `json:"grading"`
	Course     string `json:"course"`
	Approved   string `json:"approved"`
}
