// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Course struct {
	Title      string   `json:"title"`
	Number     string   `json:"number"`
	Credits    string   `json:"credits"`
	Offered    string   `json:"offered"`
	Contents   string   `json:"contents"`
	DriveFiles []string `json:"driveFiles"`
	ID         string   `json:"id"`
	Dept       string   `json:"dept"`
	Author     string   `json:"author"`
}

type CourseData struct {
	Course  *Course   `json:"course"`
	Reviews []*Review `json:"reviews"`
}

type NewCourse struct {
	Title    string `json:"title"`
	Number   string `json:"number"`
	Credits  string `json:"credits"`
	Offered  string `json:"offered"`
	Contents string `json:"contents"`
	Dept     string `json:"dept"`
	Author   string `json:"author"`
}

type Response struct {
	Ok      bool   `json:"ok"`
	Message string `json:"message"`
}

type Review struct {
	ID         string `json:"id"`
	Semester   string `json:"semester"`
	Instructor string `json:"instructor"`
	Grading    string `json:"grading"`
	Course     string `json:"course"`
	Approved   string `json:"approved"`
}

type SearchParams struct {
	Identifier string `json:"identifier"`
}

type User struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	RollNo    string `json:"rollNo"`
	Banned    bool   `json:"banned"`
	Role      string `json:"role"`
}
